### ISSUE TITLE
segway_config.sh is not found during "catkin build"

### ISSUE THREAD

**Issue by jonbinney** [StanleyInnovation/segway_v3#10]
When using catkin tools and running `catkin build`, I get ugly warnings of the form:
```
Warnings   << segway_navigation_apps:cmake 
logs/segway_navigation_apps/build.cmake.000.log                                                                                                                   
devel/.private/segway_navigation_apps/env.sh: 5: devel/etc/catkin/profile.d/50.segway_config.sh: source: not found
```

I've traced this to the line in `segway_v3_config/env-hooks/50.segway_config.sh` that reads: `source $(rospack find segway_v3_config)/segway_config.sh`

The `$(rospack find segway_v3_config)` part of that is better than the original hardcoded path, but seems to fail to resolve during a build (since of course I haven't sourced `devel/setup.bash` before the build finishes). This doesn't happen when using catkin_make, butI don't think this is an error on the part of catkin tools. I think that having an environment hook that tries to source a script in a package that is in the process of being built is a bad thing to do.

The approach of using an env-hook to create a bunch of environment variables needed only by this specific set of packages also seems to cause problems if this package is released. At that point sourcing `/opt/ros/<rosdistro>/setup.bash` on any machine that has segway_v3_config package installed would dump a ton of segway environment variables into the environment.

Can the env-hook's in segway_v3_config and segway_description be removed? That would force users to manually source these scripts, but I think that's OK, and would be better than the current setup.

**Comment by PatrickHussey** [comment]
I noticed this too, but don't really see a need to change it. There are ways around it but it would affect all environment variables or require manually sourcing. From a support standpoint it is much easier to encapsulate all this in a workspace and make it automatic; but I see your point.

I will think about it a little but I am inclined to leave it alone for now.

**Comment by PatrickHussey** [comment]
This issue has been fixed with a new method that finds the path at compile time

**Comment by jack-oquin** [comment]
This is still not working for me:
```
$ catkin build 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found
-----------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/indigo
Workspace:                   /home/joq/ros/v3
-----------------------------------------------------
Source Space:       [exists] /home/joq/ros/v3/src
Log Space:          [exists] /home/joq/ros/v3/logs
Build Space:        [exists] /home/joq/ros/v3/build
Devel Space:        [exists] /home/joq/ros/v3/devel
Install Space:      [exists] /home/joq/ros/v3/install
DESTDIR:            [unused] None
-----------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        merged
-----------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-----------------------------------------------------
[build] Found '29' packages in 0.0 seconds.                                                                                                                                     
Starting  >>> catkin_tools_prebuild                                                                                                                                             
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found                                                        
________________________________________________________________________________________________________________________________________________________________________________
Warnings   << catkin_tools_prebuild:cmake /home/joq/ros/v3/logs/catkin_tools_prebuild/build.cmake.003.log                                                                       
/home/joq/ros/v3/devel/.private/catkin_tools_prebuild/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found
cd /home/joq/ros/v3/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/joq/ros/v3/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/joq/ros/v3/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/joq/ros/v3/install; cd -
................................................................................................................................................................................
Finished  <<< catkin_tools_prebuild                 [ 1.5 seconds ]                                                                                                             
Starting  >>> ira_laser_tools                                                                                                                                                   
Starting  >>> range_sensor_filters                                                                                                                                              
Starting  >>> segway_assisted_teleop                                                                                                                                            
Starting  >>> segway_description                                                                                                                                                
Starting  >>> segway_msgs                                                                                                                                                       
Starting  >>> segway_remote_teleop                                                                                                                                              
Starting  >>> segway_upstart                                                                                                                                                    
Starting  >>> segway_v3_config                                                                                                                                                  
Starting  >>> si_utils                                                                                                                                                          
Starting  >>> ublox_serialization                                                                                                                                               
Starting  >>> velodyne_msgs                                                                                                                                                     
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found                                                        
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found                                                        
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found 0.2]                                                   
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found 0.3] [segway_remote_teleop:mkdir - 0.4]                
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not foundegway_assisted_teleop:mkdir - 0.4] [segway_remote_te... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not foundegway_assisted_teleop:mkdir - 0.6] [segway_remote_te... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not founday_assisted_teleop:mkdir - 0.7] [range_sensor_filter... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found1] [segway_msgs:mkdir - 0.2] [segway_assisted_teleop... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found2] [ira_laser_tools:mkdir - 0.0] [segway_msgs:mkdir ... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found4] [ira_laser_tools:mkdir - 0.2] [segway_msgs:mkdir ... 
/home/joq/ros/v3/install/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found6] [ira_laser_tools:mkdir - 0.5] [segway_msgs:mkdir ... 
________________________________________________________________________________________________________________________________________________________________________________
Warnings   << segway_remote_teleop:cmake /home/joq/ros/v3/logs/segway_remote_teleop/build.cmake.000.log                                                                         
/home/joq/ros/v3/devel/.private/segway_remote_teleop/env.sh: 5: /home/joq/ros/v3/install/etc/catkin/profile.d/50.segway_config.sh: source: not found
```
And much more of the same.

My workspace contains only clean up-to-date checkouts of ``segway_v3``, ``segway_v3_desktop`` and ``segway_v3_robot``.

**Comment by PatrickHussey** [comment]
The newest version uses 50.segway_config.bash.em

So you must still have an old version of segway_v3 or you might have to go into /devel/etc/catkin/profile.d and delete the old 50.segway_config.sh if you don't want to build clean

**Comment by jack-oquin** [comment]
Not sure what I'm doing wrong. My latest commit is 7c157a6. That looks the same as your master.

It was a clean checkout and a clean build using catkin_tools.

**Comment by jack-oquin** [comment]
Ahh! I just noticed that the error messages (see above) are complaining about the file being missing in the install space.  I've configured it to install as part of testing for #21.

**Comment by jack-oquin** [comment]
Following up from the hint about install space, I built it cleanly by not using an install space:
```
$ catkin config --no-install
$ catkin clean -bdiy
$ catkin build 
```
That works fine, with none of those annoying warnings. So, the fix works for devel builds, but not when doing an install.

**Comment by jack-oquin** [comment]
Why is ``segway_config.sh`` now ``segway_config.bash``? Seems like it should work with other shells. It's just a bunch of ``export`` commands.

**Comment by jack-oquin** [comment]
When I switch back to ``--install`` mode now, it's working OK . I suppose there must have been install artifacts lying around that had not gotten cleaned up correctly. Sorry for the mistake.
